name: dotnet-mqtt-demo

services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    ports:
      - "127.0.0.1:8883:8883"
    volumes:
      - type: bind
        source: ./broker/mosquitto-docker.conf
        target: /mosquitto/config/mosquitto.conf
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./broker/certs
        target: /mosquitto/certs
        read_only: true
        bind:
          create_host_path: false
