<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Device.Gateway' Or '$(MSBuildProjectName)' == 'Application.Api'">
    <None Include="$(MSBuildThisFileDirectory)appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" Condition="Exists('$(MSBuildThisFileDirectory)appsettings.json')" />
  </ItemGroup>
</Project>
