<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Device.Gateway/Device.Gateway.csproj" />
    <ProjectReference Include="../../src/Application.Api/Application.Api.csproj" />
  </ItemGroup>
</Project>
